export const CATALOG_SET_NODE_EXPANDED = 'CATALOG_SET_NODE_EXPANDED';
export const CATALOG_SET_NODE_COLLAPSED = 'CATALOG_SET_NODE_COLLAPSED';
export const CATALOG_SET_DEFAULT_NODE = 'CATALOG_SET_DEFAULT_NODE';
export const CATALOG_SET_NODE_LOCK_STATUS = 'CATALOG_SET_NODE_LOCK_STATUS';
export const CATALOG_SET_NODE_VALUE = 'CATALOG_SET_NODE_VALUE';